# Generated by Django 5.2.17 on 2026-09-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_evento_categoria_evento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
